AOD_Bid_Stats_Merge_2023
The m-code used to recreate Steves report in which he monitors the airfreight wins and losses for the import business

let
    //Data source
    Source = Excel.Workbook(Web.Contents("https://dsvcorp.sharepoint.com/teams/FORD-GlobalAirfreightAward/Shared%20Documents/General/Performance%20Metrics/AOD%20Bidding%20Stats/AOD%20Bid%20Stats%20Merge%202023.xlsx"), null, true),
    Custom1 = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    //Data cleaning
    #"Promoted Headers" = Table.PromoteHeaders(Custom1, [PromoteAllScalars=true]),
    #"Remove pre-calc_columns" = Table.RemoveColumns(#"Promoted Headers",{"Year", "Month", "Week #", "OD Lane Pairs", "Origin", "Destination", "Response (Y/N)", "Declined", "Award Confirmed", "Response Time", "Time Posted", "After Hours", "Posted During Operating Hours", "Bid During Operating Hours", "Weight (kgs)", "Cost Per KG", "Missed Kgs", "Estimated Revenue"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Remove pre-calc_columns",{{"Shipment", Int64.Type}, {"Call Date", type date}, {"Bill To", type text}, {"Shipper", type text}, {"Ready", type datetime}, {"Consignee", type text}, {"Need", type datetime}, {"Cont", Int64.Type}, {"Pounds", type number}, {"Miles", type number}, {"Response", type any}, {"Who", type text}, {"Award", type text}, {"Unit", type text}, {"Mode", type text}, {"Posted", type datetime}, {"Responded", type datetime}, {"Awarded", type datetime}}),
    //Added formula's requested by Steve
    #"Extract Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Posted])),
    #"Extract Month" = Table.AddColumn(#"Extract Year", "Month", each Date.MonthName([Posted])),
    #"Extract Week" = Table.AddColumn(#"Extract Month", "Week #", each Date.WeekOfYear([Posted])),
    //adding in destination country code held against shipper list
    #"Left join shippers origin" = Table.NestedJoin(#"Extract Week", {"Shipper"}, Import_Shippers, {"Shipper"}, "Import_Shippers", JoinKind.LeftOuter),
    #"Expanded Destination" = Table.ExpandTableColumn(#"Left join shippers origin", "Import_Shippers", {"Country"}, {"Origin.Country"}),
    #"Renamed Destination column" = Table.RenameColumns(#"Expanded Destination",{{"Origin.Country", "Destination.Country"}}),
    //adding in origin country held against the same list
    #"Left join consignee destination" = Table.NestedJoin(#"Renamed Destination column", {"Consignee"}, Import_Shippers, {"Consignee"}, "Import_Shippers", JoinKind.LeftOuter),
    #"Expanded Origin" = Table.ExpandTableColumn(#"Left join consignee destination", "Import_Shippers", {"Country"}, {"Origin.Country"}),
    //duplicated all the excel formula's sed by Steve
    #"Merged OD Lane Pair" = Table.AddColumn(#"Expanded Origin", "OD Lane Pair", each [Origin.Country] & [Destination.Country]),
    #"Added Response Y/N" = Table.AddColumn(#"Merged OD Lane Pair", "Response Y/N", each Value.Is([Response],type text)),
    #"Added Declined" = Table.AddColumn(#"Added Response Y/N", "Declined", each [Response] = "Declined"),
    #"Added Award Confirmed" = Table.AddColumn(#"Added Declined", "Award Confirmed", each [Award] = "Yes"),
    #"Added Response Time" = Table.AddColumn(#"Added Award Confirmed", "Response Time", each if [Response] = "No Response" then "NO RESPONSE" else [Responded]-[Posted]),
    #"Added Time Posted" = Table.AddColumn(#"Added Response Time", "Time Posted", each DateTime.Time([Posted])),
    #"Added After Hours" = Table.AddColumn(#"Added Time Posted", "After Hours", each [Time Posted] >= #time(19, 0, 0)),
    #"Added Weight (kgs)" = Table.AddColumn(#"Added After Hours", "Added Weight (kgs)", each [Pounds] * 0.453592),
    #"Added Missed Kgs" = Table.AddColumn(#"Added Weight (kgs)", "Missed Kgs", each if [Response Time] <> null then if [Response Time]="NO RESPONSE" then [#"Added Weight (kgs)"] else 0 else 0, Int64.Type),
    #"Added Posted During Operating Hours" = Table.AddColumn(#"Added Missed Kgs", "Posted During Operating Hours", each if Time.From([Posted]) >= Time.From(#datetime(1899, 12, 30,6, 30, 0)) and Time.From([Posted]) <= Time.From(#datetime(1899, 12, 30,17, 00, 0)) then true else false),
    #"Added Bid During Operating Hours" = Table.AddColumn(#"Added Posted During Operating Hours", "Bid During Operating Hours", each if [Responded] <> null then if Time.From([Responded]) >= Time.From(#datetime(1899, 12, 30,6, 30, 0)) 
and Time.From([Responded]) <= Time.From(#datetime(1899, 12, 30,17, 00, 0)) then true else false else "BLANK"),
    #"Added Cost per KG" = Table.AddColumn(#"Added Bid During Operating Hours", "Cost per KG", each if [Pounds] <= 100 then 0 else if [Response] = "No Response" then 0 else if [Response] = "Declined" then 0 else [Response] / ([Pounds]*0.453592)),
    //Pulling out the average of a column
    #"Created column list" = Table.Column(#"Added Cost per KG", "Cost per KG"),
    #"Removed 0's from list" = List.Select(#"Created column list", each _ <> 0),
    AverageWithoutZeros_value = List.Average(#"Removed 0's from list"),
    //Using the average to get an estimate of the missed revenue
    #"Estimated Revenue" = Table.AddColumn(#"Added Cost per KG", "newstep", each if [Cost per KG] = 0 then AverageWithoutZeros_value * [Missed Kgs] else [Response]),
    //Remade several other excel foprmula's used by Steve
    #"Changed Type Cost per KG" = Table.TransformColumnTypes(#"Added Cost per KG",{{"Cost per KG", type number}, {"Response Y/N", Int64.Type}}),
    #"Added Participation" = Table.AddColumn(#"Changed Type Cost per KG", "Participation", each if [#"Response Y/N"] > 0 then "TRUE" else "FALSE"),
    #"Filtered Rows" = Table.SelectRows(#"Added Participation", each ([OD Lane Pair] = null))
in
    #"Filtered Rows"

AOD_BID_stats_grouped_unique
Tested this logic example from Chat GPT

let
    Source = AOD_Bid_Stats_Merge_2023,
    sortedTable = Table.Sort(Source,{{"Posted", Order.Descending}}),
    GroupedTable = Table.Group(sortedTable, {"Shipment"}, {{"AllRows", each _, type table [Shipment=nullable number, max_posted_date=datetime, Call Date=nullable date, Bill To=nullable text, Shipper=nullable text, Ready=nullable datetime, Consignee=nullable text, Need=nullable datetime, Cont=nullable number, Pounds=nullable number, Miles=nullable number, Response=any, Who=nullable text, Award=nullable text, Unit=nullable text, Mode=nullable text, Posted=datetime, Responded=nullable datetime, Awarded=nullable datetime, Year=nullable number, Month=nullable text, #"Week #"=nullable number, OD Lane Pairs=nullable text, Origin=nullable text, Destination=nullable text, #"Response (Y/N)"=nullable number, Declined=nullable number, Award Confirmed=nullable number, Response Time=any, Time Posted=nullable datetime, After Hours=nullable number, Posted During Operating Hours=nullable logical, Bid During Operating Hours=nullable logical, #"Weight (kgs)"=nullable number, Cost Per KG=any, Missed Kgs=nullable number, Estimated Revenue=nullable number]}}),
    Expanded_table = Table.ExpandTableColumn(GroupedTable, "AllRows", {"Shipment", "max_posted_date", "Call Date", "Bill To", "Shipper", "Ready", "Consignee", "Need", "Cont", "Pounds", "Miles", "Response", "Who", "Award", "Unit", "Mode", "Posted", "Responded", "Awarded", "Year", "Month", "Week #", "OD Lane Pairs", "Origin", "Destination", "Response (Y/N)", "Declined", "Award Confirmed", "Response Time", "Time Posted", "After Hours", "Posted During Operating Hours", "Bid During Operating Hours", "Weight (kgs)", "Cost Per KG", "Missed Kgs", "Estimated Revenue"}, {"AllRows.Shipment", "AllRows.max_posted_date", "AllRows.Call Date", "AllRows.Bill To", "AllRows.Shipper", "AllRows.Ready", "AllRows.Consignee", "AllRows.Need", "AllRows.Cont", "AllRows.Pounds", "AllRows.Miles", "AllRows.Response", "AllRows.Who", "AllRows.Award", "AllRows.Unit", "AllRows.Mode", "AllRows.Posted", "AllRows.Responded", "AllRows.Awarded", "AllRows.Year", "AllRows.Month", "AllRows.Week #", "AllRows.OD Lane Pairs", "AllRows.Origin", "AllRows.Destination", "AllRows.Response (Y/N)", "AllRows.Declined", "AllRows.Award Confirmed", "AllRows.Response Time", "AllRows.Time Posted", "AllRows.After Hours", "AllRows.Posted During Operating Hours", "AllRows.Bid During Operating Hours", "AllRows.Weight (kgs)", "AllRows.Cost Per KG", "AllRows.Missed Kgs", "AllRows.Estimated Revenue"}),
    Unique_table = Table.Distinct(Expanded_table,{"Shipment"})
in
    Unique_table

AOD_BID_stats_grouped_unique
I had to pull from the unique table so rerun the query
let
    //importing data from excel file in sharepoint
    Source = Excel.Workbook(Web.Contents("https://dsvcorp.sharepoint.com/teams/FORD-GlobalAirfreightAward/Shared%20Documents/General/Performance%20Metrics/AOD%20Bidding%20Stats/AOD%20Bid%20Stats%20Merge%202023.xlsx"), null, true),
    Custom1 = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    //initial cleaning of the data and layout of the table
    #"Promoted Headers" = Table.PromoteHeaders(Custom1, [PromoteAllScalars=true]),
    #"Remove pre-calc_columns" = Table.RemoveColumns(#"Promoted Headers",{"Year", "Month", "Week #", "OD Lane Pairs", "Origin", "Destination", "Response (Y/N)", "Declined", "Award Confirmed", "Response Time", "Time Posted", "After Hours", "Posted During Operating Hours", "Bid During Operating Hours", "Weight (kgs)", "Cost Per KG", "Missed Kgs", "Estimated Revenue"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Remove pre-calc_columns",{{"Shipment", Int64.Type}, {"Call Date", type date}, {"Bill To", type text}, {"Shipper", type text}, {"Ready", type datetime}, {"Consignee", type text}, {"Need", type datetime}, {"Cont", Int64.Type}, {"Pounds", type number}, {"Miles", type number}, {"Response", type any}, {"Who", type text}, {"Award", type text}, {"Unit", type text}, {"Mode", type text}, {"Posted", type datetime}, {"Responded", type datetime}, {"Awarded", type datetime}}),
    //extracting datapoints to be used in visualization filters
    #"Extract Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Posted])),
    #"Extract Month" = Table.AddColumn(#"Extract Year", "Month", each Date.MonthName([Posted])),
    #"Extract Week" = Table.AddColumn(#"Extract Month", "Week #", each Date.WeekOfYear([Posted])),
    //joining the two dataframes that contain the new data from US and MX
    #"Left join shippers origin" = Table.NestedJoin(#"Extract Week", {"Shipper"}, Import_Shippers, {"Shipper"}, "Import_Shippers", JoinKind.LeftOuter),
    #"Expanded Origin" = Table.ExpandTableColumn(#"Left join shippers origin", "Import_Shippers", {"Country"}, {"Origin.Country"}),
    //joining the new dataset into the dataset with historical data
    #"Left join consignee destination" = Table.NestedJoin(#"Expanded Origin", {"Consignee"}, Import_Shippers, {"Consignee"}, "Import_Shippers", JoinKind.LeftOuter),
    #"Expanded Destination" = Table.ExpandTableColumn(#"Left join consignee destination", "Import_Shippers", {"Country_1"}, {"Destination.Country_1"}),
    #"Merged OD Lane Pair" = Table.AddColumn(#"Expanded Destination", "OD Lane Pair", each [Origin.Country] & [Destination.Country_1]),
    //calculation based on the original sheet provided by Steve
    #"Added Response Y/N" = Table.AddColumn(#"Merged OD Lane Pair", "Response Y/N", each Value.Is([Response],type text)),
    #"Added Declined" = Table.AddColumn(#"Added Response Y/N", "Declined", each [Response] = "Declined"),
    #"Added Award Confirmed" = Table.AddColumn(#"Added Declined", "Award Confirmed", each [Award] = "Yes"),
    #"Added Response Time" = Table.AddColumn(#"Added Award Confirmed", "Response Time", each if [Response] = "No Response" then "NO RESPONSE" else [Responded]-[Posted]),
    #"Added Time Posted" = Table.AddColumn(#"Added Response Time", "Time Posted", each DateTime.Time([Posted])),
    #"Added After Hours" = Table.AddColumn(#"Added Time Posted", "After Hours", each [Time Posted] >= #time(19, 0, 0)),
    #"Added Weight (kgs)" = Table.AddColumn(#"Added After Hours", "Added Weight (kgs)", each [Pounds] * 0.453592),
    #"Added Missed Kgs" = Table.AddColumn(#"Added Weight (kgs)", "Missed Kgs", each if [Response Time] <> null then if [Response Time]="NO RESPONSE" then [#"Added Weight (kgs)"] else 0 else 0, Int64.Type),
    #"Added Posted During Operating Hours" = Table.AddColumn(#"Added Missed Kgs", "Posted During Operating Hours", each if Time.From([Posted]) >= Time.From(#datetime(1899, 12, 30,6, 30, 0)) and Time.From([Posted]) <= Time.From(#datetime(1899, 12, 30,17, 00, 0)) then true else false),
    #"Added Bid During Operating Hours" = Table.AddColumn(#"Added Posted During Operating Hours", "Bid During Operating Hours", each if [Responded] <> null then if Time.From([Responded]) >= Time.From(#datetime(1899, 12, 30,6, 30, 0)) 
and Time.From([Responded]) <= Time.From(#datetime(1899, 12, 30,17, 00, 0)) then true else false else "BLANK"),
    #"Added Cost per KG" = Table.AddColumn(#"Added Bid During Operating Hours", "Cost per KG", each if [Pounds] <= 100 then 0 else if [Response] = "No Response" then 0 else if [Response] = "Declined" then 0 else [Response] / ([Pounds]*0.453592)),
    //steps to determine the average of the Cost per KG column used in the Estimated Revenue column
    #"Created column list" = Table.Column(#"Added Cost per KG", "Cost per KG"),
    #"Removed 0's from list" = List.Select(#"Created column list", each _ <> 0),
    AverageWithoutZeros_value = List.Average(#"Removed 0's from list"),
    #"Estimated Revenue" = Table.AddColumn(#"Added Cost per KG", "newstep", each if [Cost per KG] = 0 then AverageWithoutZeros_value * [Missed Kgs] else [Response]),
    #"Changed Type Cost per KG" = Table.TransformColumnTypes(#"Added Cost per KG",{{"Cost per KG", type number}}),
    //removing duplicate shipments from logic
    #"Sorted Rows" = Table.Sort(#"Changed Type Cost per KG",{{"Posted", Order.Descending}}),
    #"Removed Duplicates1" = Table.Distinct(#"Sorted Rows", {"Shipment"}),
    //grouping results to allow for a per lane pair analysis
    #"Added Award_no_response_removed" = Table.AddColumn(#"Removed Duplicates1", "Award_no_response_removed", each if [Response] = "No Response" then 0 else if [Response] = "Declined" then 0 else [Response]),
    #"Changed Award confirmed to int" = Table.TransformColumnTypes(#"Added Award_no_response_removed",{{"Award Confirmed", Int64.Type}, {"Response Y/N", Int64.Type}}),
    #"Grouped Rows" = Table.Group(#"Changed Award confirmed to int", {"OD Lane Pair"}, {{"Sum_weight", each List.Sum([#"Added Weight (kgs)"]), type number}, {"Count_awarded", each List.Sum([Award Confirmed]), type nullable number}, {"Count_Responded", each List.Sum([#"Response Y/N"]), type logical}, {"Sum_awarded", each List.Sum([Award_no_response_removed]), type number}})
in
    #"Grouped Rows"


Rate data code
Code used to clean up the rate data table
let
    Source = Excel.CurrentWorkbook(){[Name="tbl_rate_data"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"DSV Lane ID", type text}, {"SERVICE", type text}, {"ORIGIN REGION", type text}, {"ORIGIN COUNTRY", type text}, {"DESTINATION COUNTRY", type text}, {"OD Pair", type text}, {"TRANSIT TIME REQUIREMENT (HRS)", type text}, {"CURRENCY", type text}, {"AIRFREIGHT MIN", Int64.Type}, {"<500KG", type number}, {"+500KG", type number}, {"+1000KG", type number}, {"FSC (PER KG)", type number}, {"SSC (PER KG)", type number}, {"Oversize Surcharge", type any}, {"Update Date", type text}, {"Update User", type text}, {"Comments ", type text}, {"Validation_date", type datetime}, {"count", type text}}),
    #"Added Key_column" = Table.AddColumn(#"Changed Type", "Key_column", each [DSV Lane ID] & [Update Date] & [count]),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Key_column",{"Key_column", "SERVICE", "ORIGIN REGION", "ORIGIN COUNTRY", "DESTINATION COUNTRY", "OD Pair", "TRANSIT TIME REQUIREMENT (HRS)", "CURRENCY", "AIRFREIGHT MIN", "<500KG", "+500KG", "+1000KG", "FSC (PER KG)", "SSC (PER KG)", "Oversize Surcharge", "Update Date", "Update User", "Comments "}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "+500KG Total", each [#"+500KG"]+[#"+1000KG"]+[#"FSC (PER KG)"]+[#"SSC (PER KG)"]),
    #"Added OD Lane Pairs" = Table.AddColumn(#"Added Custom", "Merged OD Lane Pairs", each [ORIGIN COUNTRY] & [DESTINATION COUNTRY])
in
    #"Added OD Lane Pairs"

Import shippers table
let
    Source = Excel.CurrentWorkbook(){[Name="Shippers"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type any}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Shipper", type text}, {"Country", type text}, {"Column3", type any}, {"Consignee", type text}, {"Country_1", type text}, {"State", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Column3"})
in
    #"Removed Columns"

Latest rates table

let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"DSV Lane ID" = _t, Key_column = _t, SERVICE = _t, #"ORIGIN REGION" = _t, #"ORIGIN COUNTRY" = _t, #"DESTINATION COUNTRY" = _t, #"OD Pair" = _t, #"TRANSIT TIME REQUIREMENT (HRS)" = _t, CURRENCY = _t, #"AIRFREIGHT MIN" = _t, #"<500KG" = _t, #"+500KG" = _t, #"+1000KG" = _t, #"FSC (PER KG)" = _t, #"SSC (PER KG)" = _t, #"Oversize Surcharge" = _t, #"Update Date" = _t, #"Update User" = _t, Validation_date = _t, count = _t, Comments = _t, #"+500KG Total" = _t, #"Merged OD Lane Pairs" = _t, #"<100KG" = _t, #"Adding datetime stamp" = _t, #"Extract day from datetimestamp" = _t, #"Extract year of datetime stamp" = _t]),
    #"Appended merge_MXUS_Rate" = Table.Combine({Source, merge_MXUS_Rate}),
    #"Changed Type" = Table.TransformColumnTypes(#"Appended merge_MXUS_Rate",{{"DSV Lane ID", type text}, {"Key_column", type text}, {"SERVICE", type text}, {"ORIGIN REGION", type text}, {"ORIGIN COUNTRY", type text}, {"DESTINATION COUNTRY", type text}, {"OD Pair", type text}, {"TRANSIT TIME REQUIREMENT (HRS)", type text}, {"CURRENCY", type text}, {"AIRFREIGHT MIN", type text}, {"<500KG", type text}, {"+500KG", type text}, {"+1000KG", type text}, {"FSC (PER KG)", type text}, {"SSC (PER KG)", type text}, {"Oversize Surcharge", type text}, {"Update Date", type text}, {"Update User", type text}, {"Validation_date", type text}, {"count", type text}, {"Comments", type text}, {"+500KG Total", type text}, {"Merged OD Lane Pairs", type text}, {"<100KG", type text}, {"Adding datetime stamp", type text}, {"Extract day from datetimestamp", type text}, {"Extract year of datetime stamp", type text}}),
    #"Added Key_column_2" = Table.AddColumn(#"Changed Type", "Key_column_2", each [DSV Lane ID] & [Update Date]),
    #"Changed DSV Lane ID" = Table.TransformColumnTypes(#"Added Key_column_2",{{"DSV Lane ID", type text}}),
    #"Changed Update Date" = Table.TransformColumnTypes(#"Changed DSV Lane ID",{{"Update Date", type text}}),
    #"Changed Key_column" = Table.TransformColumnTypes(#"Changed Update Date",{{"Key_column", type text}, {"Key_column_2", type text}}),
    #"Grouped DSV Lane ID" = Table.Group(#"Changed Key_column", {"DSV Lane ID"}, {{"Latest update date", each List.Max([Update Date]), type text}}),
    #"Merged two columns" = Table.CombineColumns(#"Grouped DSV Lane ID",{"DSV Lane ID", "Latest update date"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Merged"),
    #"Added Index" = Table.AddColumn(#"Merged two columns", "Index Column", each 1),
    Merged_data_sets = Table.Join(#"Added Index", "Merged",#"Changed Key_column", "Key_column_2"),
    #"Changed SERVICE" = Table.TransformColumnTypes(Merged_data_sets,{{"SERVICE", type text}}),
    #"Added final_filter" = Table.AddColumn(#"Changed SERVICE", "final_filter", each [SERVICE] & [Key_column_2]),
    #"Changed final_filter" = Table.TransformColumnTypes(#"Added final_filter",{{"final_filter", type text}}),
    #"Removed Duplicates final_filter" = Table.Distinct(#"Changed final_filter", {"final_filter"}),
    #"Removed unneeded columns" = Table.RemoveColumns(#"Removed Duplicates final_filter",{"Index Column", "Key_column", "Key_column_2", "final_filter"})
in
    #"Removed unneeded columns"