M-Code frequestly used logic

**Define Operating Hours:**
= Table.AddColumn(#"Added Missed Kgs", "Posted During Operating Hours", each if Time.From([Posted]) >= Time.From(#datetime(1899, 12, 30,6, 30, 0)) 
and Time.From([Posted]) <= Time.From(#datetime(1899, 12, 30,17, 00, 0)) then true else false)

**Keep populating even when there are null values:**
= Table.AddColumn(#"Added Weight (kgs)", "Missed Kgs", each if [Response Time] <> null then if [Response Time]="NO RESPONSE" 
then [#"Added Weight (kgs)"] else 0 else 0, Int64.Type)


